server:
  port: 8084  # Payments microservice runs on port 8084

spring:
  application:
    name: "payments"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://mysql:3306/paymentsdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
#    ?createDatabaseIfNotExist=true allowPublicKeyRetrieval=true&
    username: root #zhaksylyk
    password: root #zhaksylyk
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
