server:
  port: 8084  # Payments microservice runs on port 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentsdb?allowPublicKeyRetrieval=true&useSSL=false
#    ?createDatabaseIfNotExist=true allowPublicKeyRetrieval=true&
    username: root #zhaksylyk
    password: root #zhaksylyk
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

#  application:
#    name: payments-microservice
