version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: zhaksylyk
      MONGO_INITDB_ROOT_PASSWORD: zhaksylyk
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: zhaksylyk
      ME_CONFIG_MONGODB_ADMINPASSWORD: zhaksylyk
      ME_CONFIG_MONGODB_SERVER: mongodb
      # Explicitly set the URL, including authSource=admin
      ME_CONFIG_MONGODB_URL: "mongodb://zhaksylyk:zhaksylyk@mongodb:27017/?authSource=admin"
    depends_on:
      - mongodb

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: tripsdb
#      MYSQL_USER: zhaksylyk
#      MYSQL_PASSWORD: zhaksylyk
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d  # Mount custom init scripts

# RUN THIS ON TERMINAL AFTER DOCKER COMPOSE UP
#      docker exec -it mysql mysql -u root -p (PASSWORD IS ALSO ROOT)
#      SOURCE /docker-entrypoint-initdb.d/init.sql;
#      SHOW DATABASES;



volumes:
  mongodb_data:
  mysql_data: