server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://zhaksylyk:zhaksylyk@localhost:27017/passengerdb?authSource=admin
#      database: passengerdb
#      username: zhaksylyk
#      password: zhaksylyk
#      authentication-database: admin
#      host: localhost
#      port: 27017