server:
  port: 8080

spring:
  application:
    name: "passengers"
  profiles:
    active: "prod"
  data:
    mongodb:
      uri: mongodb://zhaksylyk:zhaksylyk@mongodb:27017/passengerdb?authSource=admin
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"