server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/tripsdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
#    createDatabaseIfNotExist=true&u&
    username: root #zhaksylyk
    password: root #zhaksylyk
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect